stages:
  generate:
    cmd: python src/generate_data.py --n 5000 --seed 42
    deps:
      - src/generate_data.py
    outs:
      - data/raw/dataset.csv

  validate:
    cmd: python src/validate_data.py
    deps:
      - src/validate_data.py
      - data/raw/dataset.csv

  preprocess:
    cmd: python src/preprocess.py
    deps:
      - src/preprocess.py
      - data/raw/dataset.csv
    outs:
      - data/processed/train.csv
      - data/processed/test.csv

  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/processed/train.csv

  evaluate:
    cmd: python src/evaluate.py
    deps:
      - src/evaluate.py
      - data/processed/test.csv
    metrics:
      - metrics/metrics.json
